### ISSUE TITLE
invalid line break should be user error

### ISSUE THREAD

**Issue by odinuv** [keboola/processor-create-manifest#7]
Fatal error: Uncaught Keboola\Csv\InvalidArgumentException: Invalid line break. Please use unix \n or win \r\n line breaks. in /code/vendor/keboola/csv/src/Keboola/Csv/CsvFile.php:162
Stack trace:
#0 /code/vendor/keboola/csv/src/Keboola/Csv/CsvFile.php(268): Keboola\Csv\CsvFile->validateLineBreak()
#1 /code/vendor/keboola/csv/src/Keboola/Csv/CsvFile.php(262): Keboola\Csv\CsvFile->_readLine()
#2 /code/vendor/keboola/csv/src/Keboola/Csv/CsvFile.php(102): Keboola\Csv\CsvFile->rewind()
#3 /code/main.php(101): Keboola\Csv\CsvFile->getHeader()
#4 {main}
thrown in /code/vendor/keboola/csv/src/Keboola/Csv/CsvFile.php on line 162

**Comment by odinuv** [comment]
fixed in 9310f3c68bd4b47fcba776140b601f51638dad7b
